specVersion: 1.0.0
name: collator-indexer
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Astar collators indexer project
repository: 'https://github.com/subquery/astar-subql-starters'
schema:
  file: ./schema.graphql
# network:
#   chainId: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108' #Shiden
#   endpoint: 'wss://rpc.shiden.astar.network'
#   dictionary: 'https://api.subquery.network/sq/subquery/shiden-dictionary'
#   chaintypes:
#     file: ./dist/chaintypes.js
network:
  chainId: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6' #Astar
  endpoint: 'wss://rpc.astar.network'
  dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 5700000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
